=== RoryQ/calendar-hack/public/schema/plan-schema.json
{
    "description": "Plan schema",
    "$id": "https://defy.org/plan",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "pattern": "^[a-z0-9]+(?:_[a-z0-9]+)*$"
        },
        "name": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "type": {
            "enum": [
                "Base",
                "Multiple Distances",
                "Marathon",
                "Half Marathon",
                "5K",
                "10K",
                "15k/10m",
                "50K",
                "100K",
                "100M"
            ]
        },
        "units": {
            "enum": [
                "mi",
                "km"
            ]
        },
        "source": {
            "type": "string"
        },
        "schedule": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/week"
            },
            "minItems": 1
        }
    },
    "required": [
        "id",
        "name",
        "description",
        "units",
        "source",
        "type",
        "schedule"
    ],
    "definitions": {
        "week": {
            "type": "object",
            "properties": {
                "description": {"type": "string"},
                "distance": {"type": "number"},
                "workouts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/workout"
                    },
                    "minItems": 7,
                    "maxItems": 7
                }
            },
            "required": [
                "workouts"
            ]
        },
        "workout": {
            "type": "object",
            "properties": {
                "title": {"type": "string"},
                "description": {"type": "string"},
                "distance": {
                    "anyOf": [
                      { "type": "number" },
                      {
                        "type": "array",
                        "items": { "type": "number" },
                        "minItems": 1,
                        "maxItems": 2
                      }
                    ]
                  },
                "tags": {
                    "type": "array",
                    "items": {
                        "enum": [
                            "Rest",
                            "Easy Run",
                            "Run",
                            "Long Run",
                            "Cross Train",
                            "Race",
                            "Speedwork",
                            "Hills"
                        ]
                    },
                    "minItems": 1,
                    "uniqueItems": true
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/step"
                    }
                }
            },
            "required": [
                "title"
            ]
        },
        "step": {
            "type": "object",
            "properties": {
                "type": {
                    "enum": ["warmup", "active", "rest", "cooldown", "repeat"]
                },
                "name": { "type": "string" },
                "duration": {
                    "type": "object",
                    "properties": {
                        "value": { "type": "number" },
                        "unit": { "enum": ["mi", "km", "m", "min", "sec"] }
                    },
                    "required": ["value", "unit"]
                },
                "target": {
                    "type": "object",
                    "properties": {
                        "type": { "enum": ["pace", "heart_rate", "power", "cadence", "open"] },
                        "value": { "type": "string" },
                        "zone": { "type": "integer" }
                    }
                },
                "count": { "type": "integer" },
                "steps": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/step" }
                }
            },
            "required": ["type"]
        }
    }
}

=== RoryQ/calendar-hack/public/plans/json/higdon_nov_half1.json
{
   "id": "higdon_nov_half1",
   "name": "Hal Higdon: Half Marathon Novice 1",
   "description": "Hal Higdon: Half Marathon Novice 1: \"The Novice 1 program is designed for beginning runners who want to prepare for their first 13.1-mile race. If 13.1 is more than enough race mileage with no desires to go 26.2 (at least for now), you have discovered one of our most gentle training programs. If you can handle the 3-to-4-mile runs prescribed in Week 1, this program will get you ready to run 13.1 week at the end of 12 weeks.\" (more details at the link below)",
   "units": "mi",
   "source": "https://www.halhigdon.com/training-programs/half-marathon-training/novice-1-half-marathon/",
   "type": "Half Marathon",
   "schedule": [
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "{2:3.2} run",
               "distance": 2
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "Rest"
            },
            {
               "title": "30 min cross"
            },
            {
               "title": "{4:6.4} run",
               "distance": 4
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "{2:3.2} run",
               "distance": 2
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "Rest"
            },
            {
               "title": "30 min cross"
            },
            {
               "title": "{4:6.4} run",
               "distance": 4
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3.5:5.6} run",
               "distance": 3.5
            },
            {
               "title": "{2:3.2} run",
               "distance": 2
            },
            {
               "title": "{3.5:5.6} run",
               "distance": 3.5
            },
            {
               "title": "Rest"
            },
            {
               "title": "40 min cross"
            },
            {
               "title": "{5:8.0} run",
               "distance": 5
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3.5:5.6} run",
               "distance": 3.5
            },
            {
               "title": "{2:3.2} run",
               "distance": 2
            },
            {
               "title": "{3.5:5.6} run",
               "distance": 3.5
            },
            {
               "title": "Rest"
            },
            {
               "title": "40 min cross"
            },
            {
               "title": "{5:8.0} run",
               "distance": 5
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{4:6.4} run",
               "distance": 4
            },
            {
               "title": "{2:3.2} run",
               "distance": 2
            },
            {
               "title": "{4:6.4} run",
               "distance": 4
            },
            {
               "title": "Rest"
            },
            {
               "title": "40 min cross"
            },
            {
               "title": "{6:9.6} run",
               "distance": 6
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{4:6.4} run",
               "distance": 4
            },
            {
               "title": "{2:3.2} run",
               "distance": 2
            },
            {
               "title": "{4:6.4} run",
               "distance": 4
            },
            {
               "title": "Rest or Easy Run"
            },
            {
               "title": "Rest"
            },
            {
               "title": "5-K Race",
               "distance": 3.1
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{4.5:7.2} run",
               "distance": 4.5
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "{4.5:7.2} run",
               "distance": 4.5
            },
            {
               "title": "Rest"
            },
            {
               "title": "50 min cross"
            },
            {
               "title": "{7:11.2} run",
               "distance": 7
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{4.5:7.2} run",
               "distance": 4.5
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "{4.5:7.2} run",
               "distance": 4.5
            },
            {
               "title": "Rest"
            },
            {
               "title": "50 min cross"
            },
            {
               "title": "{8:12.8} run",
               "distance": 8
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{5:8.0} run",
               "distance": 5
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "{5:8.0} run",
               "distance": 5
            },
            {
               "title": "Rest or Easy Run"
            },
            {
               "title": "Rest"
            },
            {
               "title": "10-K Race",
               "distance": 6.2
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{5:8.0} run",
               "distance": 5
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "{5:8.0} run",
               "distance": 5
            },
            {
               "title": "Rest"
            },
            {
               "title": "60 min cross"
            },
            {
               "title": "{9:14.4} run",
               "distance": 9
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{5:8.0} run",
               "distance": 5
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "{5:8.0} run",
               "distance": 5
            },
            {
               "title": "Rest"
            },
            {
               "title": "60 min cross"
            },
            {
               "title": "{10:16} run",
               "distance": 10
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{4:6.4} run",
               "distance": 4
            },
            {
               "title": "{3:4.6} run",
               "distance": 3
            },
            {
               "title": "{2:3.2} run",
               "distance": 2
            },
            {
               "title": "Rest"
            },
            {
               "title": "Rest"
            },
            {
               "title": "Half Marathon ({13.1:21.1})",
               "distance": 13.1
            }
         ]
      }
   ]
}

=== RoryQ/calendar-hack/public/plans/json/pfitz_multi_4.json
{
   "id": "pfitz_multi_4",
   "name": "Pfitzinger/Douglas: Multiple Marathons, 4 Weeks Between Marathons",
   "description": "Multiple Marathons 4 Weeks from \"Advanced Marathoning\" by Pete Pfitzinger and Scott Douglas",
   "units": "mi",
   "source": "https://www.amazon.com/gp/product/149256866X/",
   "type": "Marathon",
   "schedule": [
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "Recovery {5}",
               "distance": 5
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "Recovery {6}",
               "distance": 6
            },
            {
               "title": "Recovery {5}",
               "distance": 5
            },
            {
               "title": "General aerobic {8}",
               "distance": 8
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "Recovery {6}",
               "distance": 6
            },
            {
               "title": "General aerobic {8}",
               "distance": 8
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic + speed {8} w/ 8 x 100m strides",
               "distance": 8
            },
            {
               "title": "Recovery {5}",
               "distance": 5
            },
            {
               "title": "Medium-long run {11}",
               "distance": 11
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "VO₂max {8}",
               "description": "VO₂max {8} w/ 5 x 800 m @ 5K race pace; jog 50 to 90% interval time between",
               "distance": 8
            },
            {
               "title": "Recovery {5}",
               "distance": 5
            },
            {
               "title": "Medium-long run {15}",
               "distance": 15
            },
            {
               "title": "Recovery {4}",
               "distance": 4
            },
            {
               "title": "Recovery + speed {5} w/ 8 x 100 m strides",
               "distance": 5
            },
            {
               "title": "Medium-long run {11}",
               "distance": 11
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "Recovery {6}",
               "distance": 6
            },
            {
               "title": "Dress rehearsal {7} w/ {2} @ marathon race pace",
               "distance": 7
            },
            {
               "title": "Recovery {6}",
               "distance": 6
            },
            {
               "title": "Recovery + speed {5} w/ 8 x 100 m strides",
               "distance": 5
            },
            {
               "title": "Recovery {4}",
               "distance": 4
            },
            {
               "title": "Plan Ends",
               "distance": 26.2
            }
         ]
      }
   ]
}

=== RoryQ/calendar-hack/public/plans/json/pfitz_04_multi_4th.json
{
   "id": "pfitz_04_multi_4th",
   "name": "Pfitzinger/Douglas: Multiple Marathoning, 4-week schedule",
   "description": "\"Multiple Marathoning, 4-week schedule\" from \"Advanced Marathoning\" (fourth edition) by Pete Pfitzinger and Scott Douglas",
   "units": "mi",
   "source": "https://www.amazon.com/dp/1718237472/",
   "type": "Marathon",
   "schedule": [
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4,
                  5
               ]
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {5-6:8-10}",
               "distance": [
                  5,
                  6
               ]
            },
            {
               "title": "Recovery {5-6:8-10}",
               "distance": [
                  5,
                  6
               ]
            },
            {
               "title": "Recovery {6-7:10-11}",
               "distance": [
                  6,
                  7
               ]
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {6-7:10-11}",
               "distance": [
                  6,
                  7
               ]
            },
            {
               "title": "Gen-aerobic {7-8:11-13}",
               "distance": [
                  7,
                  8
               ]
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Gen-aerobic + speed {8-9:13-14} with 8 x 100 m strides",
               "distance": [
                  8,
                  9
               ]
            },
            {
               "title": "Recovery {5-6:8-10}",
               "distance": [
                  5,
                  6
               ]
            },
            {
               "title": "Gen-aerobic {10-11:16-18}",
               "distance": [
                  10,
                  11
               ]
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "V̇O₂max {8-9:13-14} with 6 x 600 m at 5K race pace; jog 50%-90% interval time",
               "distance": [
                  8,
                  9
               ]
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4,
                  5
               ]
            },
            {
               "title": "Med-long run {12-13:19-21}",
               "distance": [
                  12,
                  13
               ]
            },
            {
               "title": "Recovery {3-4:5-6}",
               "distance": [
                  3,
                  4
               ]
            },
            {
               "title": "Recovery + speed {5-6:8-10} with 8 x 100 m strides",
               "distance": [
                  5,
                  6
               ]
            },
            {
               "title": "Gen-aerobic {10-11:16-18}",
               "distance": [
                  10,
                  11
               ]
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "Recovery {5-6:8-10}",
               "distance": [
                  5,
                  6
               ]
            },
            {
               "title": "Dress rehearsal {6-7:10-11} with {2:3} at marathon pace",
               "distance": [
                  6,
                  7
               ]
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4,
                  5
               ]
            },
            {
               "title": "Recovery + speed {4-5:6-8} with 6 x 100 m strides",
               "distance": [
                  4,
                  5
               ]
            },
            {
               "title": "Recovery {2-4:3-6}",
               "distance": [
                  2,
                  4
               ]
            },
            {
               "title": "Second marathon",
               "distance": 26.2
            }
         ]
      }
   ]
}

=== RoryQ/calendar-hack/public/plans/json/frr_bt_02.json
{
   "id": "frr_bb_02",
   "name": "Faster Road Racing: Base Building Schedule 2",
   "description": "\"Base Training 2: Building up to 45 Miles (72 km) per Week\" from \"Faster Road Racing: 5K to Half Marathon\" by Pete D. Pfitzinger and Philip Latter.\"",
   "units": "mi",
   "source": "https://www.amazon.com/Faster-Road-Racing-Half-Marathon/dp/1450470459",
   "type": "Base",
   "schedule": [
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic {6:10}",
               "distance": 6
            },
            {
               "title": "General aerobic {3:5}",
               "distance": 3
            },
            {
               "title": "General aerobic {4:6}",
               "distance": 4
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic {5:9}",
               "distance": 5
            },
            {
               "title": "Endurance {9:14}",
               "distance": 9
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic {6:10}",
               "distance": 6
            },
            {
               "title": "General aerobic {3:5}",
               "distance": 3
            },
            {
               "title": "General aerobic {5:8}",
               "distance": 5
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic {6:10}",
               "distance": 6
            },
            {
               "title": "Endurance {10:16}",
               "distance": 10
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic {6:10}",
               "distance": 6
            },
            {
               "title": "General aerobic {3:5}",
               "distance": 3
            },
            {
               "title": "General aerobic {5:8}",
               "distance": 5
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic {6:10}",
               "distance": 6
            },
            {
               "title": "Endurance {10:16}",
               "distance": 10
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic {7:11}",
               "distance": 7
            },
            {
               "title": "General aerobic {3:5}",
               "distance": 3
            },
            {
               "title": "General aerobic + speed {6} w/ 8 x 100 m strides {6:10}",
               "description": "General aerobic + speed {6} w/ 8 x 100 m strides {6:10}",
               "distance": 6
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic {7:11}",
               "distance": 7
            },
            {
               "title": "Endurance {10:16}",
               "distance": 10
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic {7:11}",
               "distance": 7
            },
            {
               "title": "General aerobic {3:5}",
               "distance": 3
            },
            {
               "title": "Lactate threshold {7:11} 18 min tempo run",
               "distance": 7
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic {8:13}",
               "distance": 8
            },
            {
               "title": "Endurance {11:18}",
               "distance": 11
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic {7:11}",
               "distance": 7
            },
            {
               "title": "General aerobic {3:5}",
               "distance": 3
            },
            {
               "title": "General aerobic + speed {7} w/ 8 x 100 m strides {7:11}",
               "description": "General aerobic + speed {7} w/ 8 x 100 m strides {7:11}",
               "distance": 7
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic {8:13}",
               "distance": 8
            },
            {
               "title": "Endurance {11:18}",
               "distance": 11
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic {8:13}",
               "distance": 8
            },
            {
               "title": "General aerobic {4:6}",
               "distance": 4
            },
            {
               "title": "Lactate threshold {8:13}",
               "description": "Lactate threshold {8:13}\n20 min tempo run",
               "distance": 7
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic {8:13}",
               "distance": 8
            },
            {
               "title": "Endurance {11:18}",
               "distance": 11
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic {9:14}",
               "distance": 9
            },
            {
               "title": "General aerobic {4:6}",
               "distance": 4
            },
            {
               "title": "General aerobic + speed {8} w/ 8 x 100 m strides {8:13}",
               "description": "General aerobic + speed {8} w/ 8 x 100 m strides {8:13}",
               "distance": 7
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic {9:14}",
               "distance": 9
            },
            {
               "title": "Endurance {12:19}",
               "distance": 12
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic {9:14}",
               "distance": 9
            },
            {
               "title": "General aerobic {4:6}",
               "distance": 4
            },
            {
               "title": "Lactate threshold {8:13}",
               "description": "Lactate threshold {8:13}\n22 min tempo run",
               "distance": 8
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic {9:14}",
               "distance": 9
            },
            {
               "title": "Endurance {12:19}",
               "distance": 12
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic {10:16}",
               "distance": 10
            },
            {
               "title": "General aerobic {5:8}",
               "distance": 4
            },
            {
               "title": "General aerobic + speed {8} w/ 8 x 100 m strides {8:13}",
               "description": "General aerobic + speed {8} w/ 8 x 100 m strides {8:13}",
               "distance": 8
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic {10:16}",
               "distance": 10
            },
            {
               "title": "Endurance {12:19}",
               "distance": 12
            }
         ]
      }
   ]
}
