=== RoryQ/calendar-hack/public/schema/plan-schema.json
{
    "description": "Plan schema",
    "$id": "https://defy.org/plan",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "pattern": "^[a-z0-9]+(?:_[a-z0-9]+)*$"
        },
        "name": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "type": {
            "enum": [
                "Base",
                "Multiple Distances",
                "Marathon",
                "Half Marathon",
                "5K",
                "10K",
                "15k/10m",
                "50K",
                "100K",
                "100M"
            ]
        },
        "units": {
            "enum": [
                "mi",
                "km"
            ]
        },
        "source": {
            "type": "string"
        },
        "schedule": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/week"
            },
            "minItems": 1
        }
    },
    "required": [
        "id",
        "name",
        "description",
        "units",
        "source",
        "type",
        "schedule"
    ],
    "definitions": {
        "week": {
            "type": "object",
            "properties": {
                "description": {"type": "string"},
                "distance": {"type": "number"},
                "workouts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/workout"
                    },
                    "minItems": 7,
                    "maxItems": 7
                }
            },
            "required": [
                "workouts"
            ]
        },
        "workout": {
            "type": "object",
            "properties": {
                "title": {"type": "string"},
                "description": {"type": "string"},
                "distance": {
                    "anyOf": [
                      { "type": "number" },
                      {
                        "type": "array",
                        "items": { "type": "number" },
                        "minItems": 1,
                        "maxItems": 2
                      }
                    ]
                  },
                "tags": {
                    "type": "array",
                    "items": {
                        "enum": [
                            "Rest",
                            "Easy Run",
                            "Run",
                            "Long Run",
                            "Cross Train",
                            "Race",
                            "Speedwork",
                            "Hills"
                        ]
                    },
                    "minItems": 1,
                    "uniqueItems": true
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/step"
                    }
                }
            },
            "required": [
                "title"
            ]
        },
        "step": {
            "type": "object",
            "properties": {
                "type": {
                    "enum": ["warmup", "active", "rest", "cooldown", "repeat"]
                },
                "name": { "type": "string" },
                "duration": {
                    "type": "object",
                    "properties": {
                        "value": { "type": "number" },
                        "unit": { "enum": ["mi", "km", "m", "min", "sec"] }
                    },
                    "required": ["value", "unit"]
                },
                "target": {
                    "type": "object",
                    "properties": {
                        "type": { "enum": ["pace", "heart_rate", "power", "cadence", "open"] },
                        "value": { "type": "string" },
                        "zone": { "type": "integer" }
                    }
                },
                "count": { "type": "integer" },
                "steps": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/step" }
                }
            },
            "required": ["type"]
        }
    }
}

=== RoryQ/calendar-hack/public/plans/json/pfitz_04_multi.json
{
   "id": "pfitz_04_multi",
   "name": "Pfitzinger/Douglas: Multiple Marathoning, 4-week schedule",
   "description": "\"Multiple Marathoning, 4-week schedule\" from \"Advanced Marathoning\" (third edition) by Pete Pfitzinger and Scott Douglas",
   "units": "mi",
   "source": "https://www.amazon.com/gp/product/149256866X/",
   "type": "Marathon",
   "schedule": [
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {6:10}",
               "distance": 6
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5
            },
            {
               "title": "Gen-aerobic {8:13}",
               "distance": 8
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {6:10}",
               "distance": 6
            },
            {
               "title": "Gen-aerobic {8:13}",
               "distance": 8
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Gen-aerobic + speed {8:13} with 8 x 100 m strides",
               "distance": 8
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5
            },
            {
               "title": "Med-long run {11:18}",
               "distance": 11
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "VO₂max {8:13} with 5 x 800 m at 5K race pace; jog 50-90% interval time",
               "distance": 8
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5
            },
            {
               "title": "Med-long run {15:24}",
               "distance": 15
            },
            {
               "title": "Recovery {4:6}",
               "distance": 4
            },
            {
               "title": "Recovery + speed {5:8} with 8 x 100 m strides",
               "distance": 5
            },
            {
               "title": "Med-long run {11:18}",
               "distance": 11
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "Recovery {6:10}",
               "distance": 6
            },
            {
               "title": "Dress rehearsal {7:11} with {2:3} at marathon pace",
               "distance": 7
            },
            {
               "title": "Recovery {6:10}",
               "distance": 6
            },
            {
               "title": "Recovery + speed {5:8} with 6 x 100 m strides",
               "distance": 5
            },
            {
               "title": "Recovery {4:6}",
               "distance": 4
            },
            {
               "title": "Second Marathon",
               "distance": 26.2
            }
         ]
      }
   ]
}

=== RoryQ/calendar-hack/public/plans/json/higdon_nov_half2.json
{
   "id": "higdon_nov_half1",
   "name": "Hal Higdon: Half Marathon Novice 2",
   "description": "Hal Higdon: Half Marathon Novice 2 fills the gap between the former Novice (now Novice 1) half marathon program and the Intermediate programs. Pace runs in the plan are  at the pace you plan to run in the race you’re training for.",
   "units": "mi",
   "source": "https://www.halhigdon.com/training-programs/half-marathon-training/novice-2-half-marathon/",
   "type": "Half Marathon",
   "schedule": [
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "Rest"
            },
            {
               "title": "{4:6.4} run",
               "distance": 4
            },
            {
               "title": "60 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "{3:4.8} pace",
               "distance": 3
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "Rest"
            },
            {
               "title": "{5:8.1} run",
               "distance": 5
            },
            {
               "title": "60 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "{4:6.4} run",
               "distance": 4
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "Rest"
            },
            {
               "title": "{6:9.7} run",
               "distance": 6
            },
            {
               "title": "60 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "{4:6.4} pace",
               "distance": 4
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "Rest"
            },
            {
               "title": "{7:11.3} run",
               "distance": 7
            },
            {
               "title": "60 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "{4:6.4} run",
               "distance": 4
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "Rest"
            },
            {
               "title": "{8:12.9} run",
               "distance": 8
            },
            {
               "title": "60 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "{4:6.4} pace",
               "distance": 4
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "Rest"
            },
            {
               "title": "5K race",
               "distance": 3.1
            },
            {
               "title": "60 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "{5:8.1} run",
               "distance": 5
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "Rest"
            },
            {
               "title": "{9:14.5} run",
               "distance": 9
            },
            {
               "title": "60 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "{5:8.1} pace",
               "distance": 5
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "Rest"
            },
            {
               "title": "{10:16.1} run",
               "distance": 10
            },
            {
               "title": "60 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "{5:8.1} run",
               "distance": 5
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "Rest"
            },
            {
               "title": "10K race",
               "distance": 6.2
            },
            {
               "title": "60 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "{5:8.1} pace",
               "distance": 5
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "Rest"
            },
            {
               "title": "{11:17.7} run",
               "distance": 11
            },
            {
               "title": "60 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "{5:8.1} run",
               "distance": 5
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "Rest"
            },
            {
               "title": "{12:19.3} run",
               "distance": 12
            },
            {
               "title": "60 min cross"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "{3:4.8} run",
               "distance": 3
            },
            {
               "title": "{2:3.2} run",
               "distance": 2
            },
            {
               "title": "{2:3.2} run",
               "distance": 2
            },
            {
               "title": "Rest"
            },
            {
               "title": "Rest"
            },
            {
               "title": "Half Marathon ({13.1:21.1})",
               "distance": 13.1
            }
         ]
      }
   ]
}

=== RoryQ/calendar-hack/public/plans/json/pfitz_12_55.json
{
   "id": "pfitz_12_55",
   "name": "Pfitzinger/Douglas: Up to 55 miles per week, 12-week schedule",
   "description": "\"Up to 55 miles per week, 12-week schedule\" from \"Advanced Marathoning\" (third edition) by Pete Pfitzinger and Scott Douglas",
   "units": "mi",
   "source": "https://www.amazon.com/gp/product/149256866X/",
   "type": "Marathon",
   "schedule": [
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Gen-aerobic + speed {8:13} with 6 x 10 sec hill sprints + 8 x 100 m strides",
               "distance": 8
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Gen-aerobic {9:14}",
               "distance": 9
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5
            },
            {
               "title": "Marathon-pace run {13:21} with {8:13} at marathon pace",
               "distance": 13
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Med-long run {11:18}",
               "distance": 11
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "LT {8:13} with {4:6} at LT pace",
               "distance": 8
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5
            },
            {
               "title": "Med-long run {15:24}",
               "distance": 15
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Gen-aerobic + speed {8:13} with 6 x 10 sec hill sprints + 8 X 100 m strides",
               "distance": 8
            },
            {
               "title": "Recovery {4:6}",
               "distance": 4
            },
            {
               "title": "Med-long run {11:18}",
               "distance": 11
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {4:6}",
               "distance": 4
            },
            {
               "title": "Marathon-pace run {16:26} with {10:16} at marathon pace",
               "distance": 16
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5
            },
            {
               "title": "LT {10:16} with {5:8} at LT pace",
               "distance": 10
            },
            {
               "title": "Med-long run {11:18}",
               "distance": 11
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5
            },
            {
               "title": "Long run {17:27}",
               "distance": 17
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Med-long run {12:19}",
               "distance": 12
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "LT {9:14} with {4:6} at LT pace",
               "distance": 9
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5
            },
            {
               "title": "Long run {16:26}",
               "distance": 16
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5
            },
            {
               "title": "VO₂max {10:16} with 5 x 1,000 m at 5K race pace; jog 50-90% interval time",
               "distance": 10
            },
            {
               "title": "Med-long run {12:19}",
               "distance": 12
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery + speed {6:10} with 6 x 100 m strides",
               "distance": 6
            },
            {
               "title": "Marathon-pace run {15:24} with {12:19} at marathon pace",
               "distance": 15
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery + speed {6:10} with 6 x 100 m strides",
               "distance": 6
            },
            {
               "title": "Med-long run {12:19}",
               "distance": 12
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "LT {12:19} with {7:11} at LT pace",
               "distance": 12
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5
            },
            {
               "title": "Long run {20:32}",
               "distance": 20
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "VO₂max {8:13} with 5 x 600 m at 5K race pace; jog 50-90% interval time",
               "distance": 8
            },
            {
               "title": "Med-long run {11:18}",
               "distance": 11
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery + speed {4:6} with 6 x 100 m strides",
               "distance": 4
            },
            {
               "title": "8K-15K tune-up race (total {9-13:14-21})",
               "distance": [
                  9,
                  13
               ]
            },
            {
               "title": "Long run {17:27}",
               "distance": 17
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery + speed {7:11} with 6 x 100 m strides",
               "distance": 7
            },
            {
               "title": "VO₂max {10:16} with 4 x 1,200 m at 5K race pace; jog 50-90% interval time",
               "distance": 10
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Med-long run {11:18}",
               "distance": 11
            },
            {
               "title": "Recovery {4:6}",
               "distance": 4
            },
            {
               "title": "Long run {20:32}",
               "distance": 20
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "VO₂max {8:13} with 5 x 600 m at 5K race pace; jog 50-90% interval time",
               "distance": 8
            },
            {
               "title": "Recovery {6:10}",
               "distance": 6
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery + speed {4:6} with 6 x 100 m strides",
               "distance": 4
            },
            {
               "title": "8K-10K tune-up race (total {9-11:14-18})",
               "distance": [
                  9,
                  11
               ]
            },
            {
               "title": "Long run {16:26}",
               "distance": 16
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery + speed {7:11} with 8 x 100 m strides",
               "distance": 7
            },
            {
               "title": "VO₂max {8:13} with 4 x 1,200 m at 5K race pace; jog 50-90% interval time",
               "distance": 8
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery + speed {5:8} with 6 x 100 m strides",
               "distance": 5
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Med-long run {12:19}",
               "distance": 12
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "Recovery {6:10}",
               "distance": 6
            },
            {
               "title": "Dress rehearsal {7:11} with {2:3} at marathon pace",
               "distance": 7
            },
            {
               "title": "Rest"
            },
            {
               "title": "Recovery + speed {5:8} with 6 x 100 m strides",
               "distance": 5
            },
            {
               "title": "Recovery {4:6}",
               "distance": 4
            },
            {
               "title": "Plan Ends",
               "distance": 26.2
            }
         ]
      }
   ]
}
