=== RoryQ/calendar-hack/public/schema/plan-schema.json
{
    "description": "Plan schema",
    "$id": "https://defy.org/plan",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "pattern": "^[a-z0-9]+(?:_[a-z0-9]+)*$"
        },
        "name": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "type": {
            "enum": [
                "Base",
                "Multiple Distances",
                "Marathon",
                "Half Marathon",
                "5K",
                "10K",
                "15k/10m",
                "50K",
                "100K",
                "100M"
            ]
        },
        "units": {
            "enum": [
                "mi",
                "km"
            ]
        },
        "source": {
            "type": "string"
        },
        "schedule": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/week"
            },
            "minItems": 1
        }
    },
    "required": [
        "id",
        "name",
        "description",
        "units",
        "source",
        "type",
        "schedule"
    ],
    "definitions": {
        "week": {
            "type": "object",
            "properties": {
                "description": {"type": "string"},
                "distance": {"type": "number"},
                "workouts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/workout"
                    },
                    "minItems": 7,
                    "maxItems": 7
                }
            },
            "required": [
                "workouts"
            ]
        },
        "workout": {
            "type": "object",
            "properties": {
                "title": {"type": "string"},
                "description": {"type": "string"},
                "distance": {
                    "anyOf": [
                      { "type": "number" },
                      {
                        "type": "array",
                        "items": { "type": "number" },
                        "minItems": 1,
                        "maxItems": 2
                      }
                    ]
                  },
                "tags": {
                    "type": "array",
                    "items": {
                        "enum": [
                            "Rest",
                            "Easy Run",
                            "Run",
                            "Long Run",
                            "Cross Train",
                            "Race",
                            "Speedwork",
                            "Hills"
                        ]
                    },
                    "minItems": 1,
                    "uniqueItems": true
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/step"
                    }
                }
            },
            "required": [
                "title"
            ]
        },
        "step": {
            "type": "object",
            "properties": {
                "type": {
                    "enum": ["warmup", "active", "rest", "cooldown", "repeat"]
                },
                "name": { "type": "string" },
                "duration": {
                    "type": "object",
                    "properties": {
                        "value": { "type": "number" },
                        "unit": { "enum": ["mi", "km", "m", "min", "sec"] }
                    },
                    "required": ["value", "unit"]
                },
                "target": {
                    "type": "object",
                    "properties": {
                        "type": { "enum": ["pace", "heart_rate", "power", "cadence", "open"] },
                        "value": { "type": "string" },
                        "zone": { "type": "integer" }
                    }
                },
                "count": { "type": "integer" },
                "steps": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/step" }
                }
            },
            "required": ["type"]
        }
    }
}

=== RoryQ/calendar-hack/public/plans/json/pfitz_85_recovery_4th.json
{
   "id": "pfitz_85_recovery_4th",
   "name": "Pfitzinger/Douglas: Marathon 70 to 85 Miles per Week Recovery",
   "description": "\"70 to 85 Miles per Week Recovery: Training Block 5 - Recovery\" from \"Advanced Marathoning\" (fourth edition) by Pete Pfitzinger and Scott Douglas",
   "units": "mi",
   "source": "https://www.amazon.com/dp/1718237472/",
   "type": "Marathon",
   "schedule": [
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {3-4:5-6}",
               "distance": [
                  3,
                  4
               ]
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4,
                  5
               ]
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {6-7:10-11}",
               "distance": [
                  6,
                  7
               ]
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4,
                  5
               ]
            },
            {
               "title": "Recovery {5-6:8-10}",
               "distance": [
                  5,
                  6
               ]
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {5-6:8-10}",
               "distance": [
                  5,
                  6
               ]
            },
            {
               "title": "Recovery {5-6:8-10}",
               "distance": [
                  5,
                  6
               ]
            },
            {
               "title": "Gen-aerobic {9-10:14-16}",
               "distance": [
                  9,
                  10
               ]
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {6-7:10-11}",
               "distance": [
                  6,
                  7
               ]
            },
            {
               "title": "Recovery {5-6:8-10}",
               "distance": [
                  5,
                  6
               ]
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Gen-aerobic + speed {8-9:13-14} with 8 x 100 m strides",
               "distance": [
                  8,
                  9
               ]
            },
            {
               "title": "Recovery {6-7:10-11}",
               "distance": [
                  6,
                  7
               ]
            },
            {
               "title": "Gen-aerobic {9-10:14-16}",
               "distance": [
                  9,
                  10
               ]
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {5-6:8-10}",
               "distance": [
                  5,
                  6
               ]
            },
            {
               "title": "Gen-aerobic {9-10:14-16}",
               "distance": [
                  9,
                  10
               ]
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Gen-aerobic + speed {8-9:13-14} with 8 x 100 m strides",
               "distance": [
                  8,
                  9
               ]
            },
            {
               "title": "Recovery {6-7:10-11}",
               "distance": [
                  6,
                  7
               ]
            },
            {
               "title": "Med-long run {11-12:18-19}",
               "distance": [
                  11,
                  12
               ]
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {5-6:8-10}",
               "distance": [
                  5,
                  6
               ]
            },
            {
               "title": "Gen-aerobic {9-10:14-16}",
               "distance": [
                  9,
                  10
               ]
            },
            {
               "title": "Recovery {5-6:8-10}",
               "distance": [
                  5,
                  6
               ]
            },
            {
               "title": "Gen-aerobic + speed {9-10:14-16} with 8 x 100 m strides",
               "distance": [
                  9,
                  10
               ]
            },
            {
               "title": "Recovery {6-7:10-11}",
               "distance": [
                  6,
                  7
               ]
            },
            {
               "title": "Med-long run {12-13:19-21}",
               "distance": [
                  12,
                  13
               ]
            }
         ]
      }
   ]
}

=== RoryQ/calendar-hack/public/plans/json/frr_multiple_distances_01.json
{
   "id": "frr_multiple_distances_01",
   "name": "Faster Road Racing: Multiple Distances (5K to Half-Marathon) Schedule 1",
   "description": "\"This schedule is for runners who have been training 25 to 35 miles per week. If you have been running fewer than 25 miles per week, follow the base-training schedule in chapter 8 for building up to 30 miles per week before attempting this schedule. This schedule starts at 30 miles per week and gradually builds up to 42 miles with three weeks to go before your key race.\"",
   "units": "mi",
   "source": "https://www.amazon.com/Faster-Road-Racing-Half-Marathon/dp/1450470459",
   "type": "Multiple Distances",
   "schedule": [
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic + Speed {6:10}",
               "description": "General aerobic + Speed {6:10}\n6 x 12 sec uphill followed by 6 x 100m strides",
               "distance": 6
            },
            {
               "title": "Endurance {8:13}",
               "distance": 8
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "Lactate threshold {7:11}",
               "description": "Lactate threshold {7:11}\n3 x 9 min LT intervals (jog 3 min recovery)",
               "distance": 7
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "Endurance {9:14}",
               "distance": 9
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "Speed {6:10}",
               "description": "Speed {6:10}\n2 sets of 4 x 200m @ 800m to mile race pace (jog 200m recovery and 4 min between sets)",
               "distance": 6
            },
            {
               "title": "Endurance {8:13}",
               "distance": 8
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "Lactate Threshold {8:13}",
               "description": "Lactate Threshold {8:13}\n12 min LT interval (jog 4 min recovery)\n10 min LT interval (jog 4 min recovery)\n8 min LT interval",
               "distance": 8
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "Endurance {10:16}",
               "distance": 10
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic + Speed {6:10}",
               "description": "General aerobic + Speed {6:10}\n6 x 12 sec uphill followed by 6 x 100m strides",
               "distance": 6
            },
            {
               "title": "Endurance {9:14}",
               "distance": 9
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "VO2max {8:13}",
               "description": "VO2max {8:13}\n6 x 3 min uphill @ 3K-5K race effort (jog downhill recovery)",
               "distance": 8
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "Endurance {11:18}",
               "distance": 11
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "Speed {7:11}",
               "description": "2 sets of 4 x 200m @ 800m to mile race pace (jog 200m recovery and 4 min between sets)",
               "distance": 7
            },
            {
               "title": "General aerobic {7:11}",
               "distance": 7
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic {7:11}",
               "distance": 7
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General Aerobic {9:14}",
               "distance": 9
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "VO2max {8:13}",
               "description": "5 x 1000m @ 3K-5K race pace (jog 50-90% interval time recovery)",
               "distance": 8
            },
            {
               "title": "Endurance {9:14}",
               "distance": 9
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "Lactate threshold {8:13}",
               "description": "14 min LT interval (jog 4 min recovery)\n11 min LT interval (jog 4 min recovery)\n8 min LT interval",
               "distance": 8
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "Endurance {11:18}",
               "distance": 11
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "VO2max {8:13}",
               "description": "3 x 1200 m\n3 x 800 m\nAll intervals @ 3K-5K race pace (jog 50-90% interval time recovery)",
               "distance": 8
            },
            {
               "title": "Endurance {9:14}",
               "distance": 9
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic + Speed {7:11}",
               "description": "2 sets of 6 x 100 m strides (jog 3 min between sets)",
               "distance": 7
            },
            {
               "title": "Recovery {3:5}",
               "distance": 3
            },
            {
               "title": "Progression long run {12:19}",
               "description": "Increase effort steadily throughout run, last 3 miles (5K) @ LT pace",
               "distance": 12
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "Endurance {9:14}",
               "distance": 9
            },
            {
               "title": "General aerobic + speed {7:11}",
               "description": "8 x 100 m strides",
               "distance": 7
            },
            {
               "title": "Lactate threshold {9:14}",
               "description": "30 min tempo run",
               "distance": 9
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "Recovery {4:6}",
               "distance": 4
            },
            {
               "title": "Endurance {13:21}",
               "distance": 13
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic + speed {8:13}",
               "description": "2 sets of 4 x 150 m strides (jog 250 m recovery and 4 min between sets)",
               "distance": 8
            },
            {
               "title": "General aerobic {7:11}",
               "distance": 7
            },
            {
               "title": "Rest"
            },
            {
               "title": "Recovery {4:6}",
               "distance": 4
            },
            {
               "title": "5K-10K tune-up race {8:13}",
               "distance": 8
            },
            {
               "title": "Endurance {9:14}",
               "distance": 9
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic + speed {7:11}",
               "description": "8 x 100 m strides",
               "distance": 7
            },
            {
               "title": "Recovery {4:6}",
               "distance": 4
            },
            {
               "title": "VO2max {8:13}",
               "description": "3 x 1000 m\n3 x 600 m\nAll intervals @ 3K-5K race pace (jog 50-90% interval time recovery)",
               "distance": 8
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "Recovery {4:6}",
               "distance": 4
            },
            {
               "title": "General Aerobic {9:14}",
               "distance": 9
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Race pace + speed {6:10}",
               "description": "4 x 100 m strides\n15% of race distance @ race pace",
               "distance": 6
            },
            {
               "title": "Recovery {4:6}",
               "distance": 4
            },
            {
               "title": "Recovery {4:6}",
               "distance": 4
            },
            {
               "title": "Rest"
            },
            {
               "title": "Recovery {3:5}",
               "description": "4 x 100 m strides",
               "distance": 3
            },
            {
               "title": "Key race",
               "description": "Volume varies depending on race distance"
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5
            }
         ]
      }
   ]
}

=== RoryQ/calendar-hack/public/plans/json/higdon_int_half2.json
{
   "id": "higdon_int_half2",
   "name": "Hal Higdon: Half Marathon Intermediate 2",
   "description": "Hal Higdon: Half Marathon Intermediate 2: \"The main difference between Half Marathon Intermediate 1 and Intermediate 2 is that this program (Intermediate 2) features one day of speedwork. Intermediate 1 & 2 exist parallel to one another in different universes, like the Earth 1 and Earth 2 of comic book lingo. Mondays are for cross training, starting at 30 minutes, peaking at 1 hour in Week 11, one week out from your half marathon race. Tuesdays and Thursdays are easy days: 3-5 miles. In between on Wednesdays, you do speedwork, alternating tempo runs with interval training on the track. Fridays are rest days leading to some pace running on Saturdays and long runs on Sundays, starting at 5 miles, peaking at 12 miles one week before the half marathon. Half Intermediate 2, make no mistake, is for experienced runners: individuals who have left their Novice roots behind and who want to improve their performance.\" (more details at the link below)",
   "units": "mi",
   "source": "https://www.halhigdon.com/training-programs/half-marathon-training/intermediate-2-half-marathon/",
   "type": "Half Marathon",
   "schedule": [
      {
         "workouts": [
            {
               "title": "30 min cross"
            },
            {
               "distance": 3,
               "title": "{3.0:4.8} run"
            },
            {
               "title": "5 x 400 5-K pace"
            },
            {
               "distance": 3,
               "title": "{3.0:4.8} run"
            },
            {
               "title": "Rest"
            },
            {
               "distance": 3,
               "title": "{3.0:4.8} run"
            },
            {
               "distance": 5,
               "title": "{5.0:8.0} run"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "30 min cross"
            },
            {
               "distance": 3,
               "title": "{3.0:4.8} run"
            },
            {
               "title": "30 min tempo"
            },
            {
               "distance": 3,
               "title": "{3.0:4.8} run"
            },
            {
               "title": "Rest"
            },
            {
               "distance": 3,
               "title": "{3.0:4.8} pace"
            },
            {
               "distance": 6,
               "title": "{6.0:9.7} run"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "40 min cross"
            },
            {
               "distance": 3.5,
               "title": "{3.5:5.6} run"
            },
            {
               "title": "6 x 400 5-K pace"
            },
            {
               "distance": 3,
               "title": "{3.0:4.8} run"
            },
            {
               "title": "Rest"
            },
            {
               "title": "Rest"
            },
            {
               "distance": 3.1,
               "title": "5-K Race"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "40 min cross"
            },
            {
               "distance": 3.5,
               "title": "{3.5:5.6} run"
            },
            {
               "title": "35 min tempo"
            },
            {
               "distance": 3,
               "title": "{3.0:4.8} run"
            },
            {
               "title": "Rest"
            },
            {
               "distance": 3,
               "title": "{3.0:4.8} run"
            },
            {
               "distance": 7,
               "title": "{7.0:11.3} run"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "40 min cross"
            },
            {
               "distance": 4,
               "title": "{4.0:6.4} run"
            },
            {
               "title": "7 x 400 5-K pace"
            },
            {
               "distance": 3,
               "title": "{3.0:4.8} run"
            },
            {
               "title": "Rest"
            },
            {
               "distance": 3,
               "title": "{3.0:4.8} pace"
            },
            {
               "distance": 8,
               "title": "{8.0:12.9} run"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "50 min cross"
            },
            {
               "distance": 4,
               "title": "{4.0:6.4} run"
            },
            {
               "title": "40 min tempo"
            },
            {
               "distance": 3,
               "title": "{3.0:4.8} run"
            },
            {
               "title": "Rest or easy run"
            },
            {
               "title": "Rest"
            },
            {
               "distance": 6.2,
               "title": "10-K Race"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "distance": 4.5,
               "title": "{4.5:7.2} run"
            },
            {
               "title": "8 x 400 5-K pace"
            },
            {
               "distance": 3,
               "title": "{3.0:4.8} run"
            },
            {
               "title": "Rest"
            },
            {
               "distance": 4,
               "title": "{4.0:6.4} pace"
            },
            {
               "distance": 9,
               "title": "{9.0:14.5} run"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "50 min cross"
            },
            {
               "distance": 4.5,
               "title": "{4.5:7.2} run"
            },
            {
               "title": "40 min tempo"
            },
            {
               "distance": 3,
               "title": "{3.0:4.8} run"
            },
            {
               "title": "Rest"
            },
            {
               "distance": 5,
               "title": "{5.0:8.0} pace"
            },
            {
               "distance": 10,
               "title": "{10.0:16.1} run"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "60 min cross"
            },
            {
               "distance": 5,
               "title": "{5.0:8.0} run"
            },
            {
               "title": "9 x 400 5-K pace"
            },
            {
               "distance": 3,
               "title": "{3.0:4.8} run"
            },
            {
               "title": "Rest or easy run"
            },
            {
               "title": "Rest"
            },
            {
               "distance": 9.3,
               "title": "15-K Race"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "distance": 5,
               "title": "{5.0:8.0} run"
            },
            {
               "title": "45 min tempo"
            },
            {
               "distance": 3,
               "title": "{3.0:4.8} run"
            },
            {
               "title": "Rest"
            },
            {
               "distance": 5,
               "title": "{5.0:8.0} pace"
            },
            {
               "distance": 11,
               "title": "{11.0:17.7} run"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "60 min cross"
            },
            {
               "distance": 5,
               "title": "{5.0:8.0} run"
            },
            {
               "title": "10 x 400 5-K pace"
            },
            {
               "distance": 3,
               "title": "{3.0:4.8} run"
            },
            {
               "title": "Rest"
            },
            {
               "distance": 3,
               "title": "{3.0:4.8} pace"
            },
            {
               "distance": 12,
               "title": "{12.0:19.3} run"
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "distance": 4,
               "title": "{4.0:6.4} run"
            },
            {
               "title": "30 min tempo"
            },
            {
               "distance": 2,
               "title": "{2.0:3.2} run"
            },
            {
               "title": "Rest"
            },
            {
               "title": "Rest"
            },
            {
               "distance": 13.1,
               "title": "Half Marathon"
            }
         ]
      }
   ]
}
